[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

FriendLib is an application which allows to lend books between friends.
In order to support this users can manage their collection of books, add friends and see the virtual bookshelf of their friends.
Furthermore lend requests can be sent to friends and the lend status of books can be tracked.

The word FriendLib is a portmanteau of friendship and library.

The main goal of this application is to play around with different technologies, programming languages, tools and processes (e.g. AppStore deployment).

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

The following table contains the main quality goals of the solution with measureable/decidable scenarios.

[options="header",cols="1,1,2,4"]
|===
|Id |Priority|Quality Attribute| Scenarios
| Q-1 | 1 | Portability/Adaptability a|
* App should be available as webpage, iOS and Android app
| Q-2 | 2 | Ease-of-use a|
* Main features of the app should be accessible with a maximum of 3 clicks
* No user manual required to understand the features
| Q-3 | 3 | Performance efficiency a|
* The operating cost should be lower than 10€ / 1000 users / month.
|===

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

The following table contains the list of Stakeholders for the solution and its documentation along with their expectations about it.

[options="header",cols="1,3"]
|===
|Role/Name| Expectations
| Developers  | Get an overview of the solution. Understand technical decisions.
| Architects  | Have an example of the arc42 template.
| https://github.com/carlo-mr[@carlo-mr] | Learn usage of arc42, docToolchain and other tools frameworks used in the course of writing the application.
|===
